services:
  - type: web
    name: spill-backend
    env: go
    buildCommand: go build -o app .
    startCommand: ./app
    envVars:
      - key: PORT
        value: 8080
      - key: GIN_MODE
        value: release

